// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0npThsOu-lCnRjbDeDSnLoK00sCdZC4I',
    appId: '1:1042776281580:web:b29515895cb0dacd41f0c9',
    messagingSenderId: '1042776281580',
    projectId: 'flutter-firebase-texas',
    authDomain: 'flutter-firebase-texas.firebaseapp.com',
    storageBucket: 'flutter-firebase-texas.appspot.com',
    measurementId: 'G-SBX0X16768',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZeRMRp6qktqzYtYv5DEYgKdx7AwlYHXg',
    appId: '1:1042776281580:android:ca7c6af41fe961d341f0c9',
    messagingSenderId: '1042776281580',
    projectId: 'flutter-firebase-texas',
    storageBucket: 'flutter-firebase-texas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QxcYs4oGEPA_dSChg6QsDTMykFGCxuE',
    appId: '1:1042776281580:ios:f5b6924cc575084e41f0c9',
    messagingSenderId: '1042776281580',
    projectId: 'flutter-firebase-texas',
    storageBucket: 'flutter-firebase-texas.appspot.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4QxcYs4oGEPA_dSChg6QsDTMykFGCxuE',
    appId: '1:1042776281580:ios:f5b6924cc575084e41f0c9',
    messagingSenderId: '1042776281580',
    projectId: 'flutter-firebase-texas',
    storageBucket: 'flutter-firebase-texas.appspot.com',
    iosBundleId: 'com.example.tech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0npThsOu-lCnRjbDeDSnLoK00sCdZC4I',
    appId: '1:1042776281580:web:2fe6cea69d8fc98341f0c9',
    messagingSenderId: '1042776281580',
    projectId: 'flutter-firebase-texas',
    authDomain: 'flutter-firebase-texas.firebaseapp.com',
    storageBucket: 'flutter-firebase-texas.appspot.com',
    measurementId: 'G-7R470DJEBW',
  );
}
